<a href="https://colab.research.google.com/github/Ankit23-ak/-heart-disease-prediction/blob/main/heart_deases_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## HEART DISEASE PREDICTION
## ANALYSIS AND PREDICTION OF HEART DISEASE ANALYSYS USING LOGESTIC REGRESSION OF CLASSIFICATION MODEL


## dataset link

## dataset overview Skip to
content
Kaggle

Sign In

Register
Kaggle uses cookies from Google to deliver and enhance the quality of its services and to analyze traffic.
Learn more
OK, Got it.
David Lapp · Updated 6 years ago
Heart Disease Dataset
Public Health Dataset

Download

Heart Disease Dataset
About Dataset
Context
This data set dates from 1988 and consists of four databases: Cleveland, Hungary, Switzerland, and Long Beach V. It contains 76 attributes, including the predicted attribute, but all published experiments refer to using a subset of 14 of them. The "target" field refers to the presence of heart disease in the patient. It is integer valued 0 = no disease and 1 = disease.

Content
Attribute Information:

age
sex
chest pain type (4 values)
resting blood pressure
serum cholestoral in mg/dl
fasting blood sugar > 120 mg/dl
resting electrocardiographic results (values 0,1,2)
maximum heart rate achieved
exercise induced angina
oldpeak = ST depression induced by exercise relative to rest
the slope of the peak exercise ST segment
number of major vessels (0-3) colored by flourosopy
thal: 0 = normal; 1 = fixed defect; 2 = reversable defect
The names and social security numbers of the patients were recently removed from the database, replaced with dummy values.

## project approach
step1: import the library

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:
df=pd.read_csv('/content/heart (1).csv')
df.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   52    1   0       125   212    0  ...      0      1.0      2   2     3       0
1   53    1   0       140   203    1  ...      1      3.1      0   0     3       0
2   70    1   0       145   174    0  ...      1      2.6      0   0     3       0
3   61    1   0       148   203    0  ...      0      0.0      2   1     3       0
4   62    0   0       138   294    1  ...      0      1.9      1   3     2       0

[5 rows x 14 columns]

## step3: apply EDA

In [ ]:
df.shape

(1025, 14)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [ ]:
df.describe()

age          sex  ...         thal       target
count  1025.000000  1025.000000  ...  1025.000000  1025.000000
mean     54.434146     0.695610  ...     2.323902     0.513171
std       9.072290     0.460373  ...     0.620660     0.500070
min      29.000000     0.000000  ...     0.000000     0.000000
25%      48.000000     0.000000  ...     2.000000     0.000000
50%      56.000000     1.000000  ...     2.000000     1.000000
75%      61.000000     1.000000  ...     3.000000     1.000000
max      77.000000     1.000000  ...     3.000000     1.000000

[8 rows x 14 columns]

In [ ]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

## the dataset has no biasness
            

## visuals of features values

In [ ]:
sns.pairplot(df[['age','cp','thalach','target']])

### conclusion....
Min age=1; Max age=45

min chest pain=4,;max chest pain: 28

min heart Rate= 1; max heart rate: 100

True value = 100%, False value =98%

In [ ]:
plt.figure(figsize=(10,6))
sns.heatmap(df.corr(),annot=True,cmap='coolwarm',vmin=-1,vmax=1)

<Axes: >

## step 4:features selection


In [ ]:
x=df[['age','cp','thalach',]]
y=df['target']

## spiliting of data train and test

## model selection

In [ ]:
model=LogisticRegression()


In [ ]:
model.fit(x_train,y_train)

LogisticRegression()

## model fit

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

## The model to Contern Binary Classifiy Sens Model False Classification.
There for LG is a Best model

## prediction

In [ ]:
y_pred = model.predict(x_test)
y_proba = model.predict_proba(x_test)[:]

## evaluation matrix

In [ ]:
print(f"Accuracy:'{accuracy_score(y_test,y_pred):,.2f}")

Accuracy:'0.72


In [ ]:
print(f"Confusion Matrix:\n{confusion_matrix(y_test,y_pred)}")
print(f"Classification Report\n{classification_report(y_test,y_pred)}")

Confusion Matrix:
[[73 29]
 [28 75]]
Classification Report
              precision    recall  f1-score   support

           0       0.72      0.72      0.72       102
           1       0.72      0.73      0.72       103

    accuracy                           0.72       205
   macro avg       0.72      0.72      0.72       205
weighted avg       0.72      0.72      0.72       205



In [ ]:
y_pred

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1])

In [ ]:
y_proba

array([[0.59868563, 0.40131437],
       [0.56643038, 0.43356962],
       [0.69952961, 0.30047039],
       [0.33122643, 0.66877357],
       [0.61469631, 0.38530369],
       [0.80952542, 0.19047458],
       [0.94554477, 0.05445523],
       [0.85306153, 0.14693847],
       [0.11692207, 0.88307793],
       [0.87945268, 0.12054732],
       [0.24159937, 0.75840063],
       [0.75726027, 0.24273973],
       [0.28290019, 0.71709981],
       [0.1551947 , 0.8448053 ],
       [0.90927789, 0.09072211],
       [0.28231501, 0.71768499],
       [0.76756037, 0.23243963],
       [0.15786054, 0.84213946],
       [0.19108487, 0.80891513],
       [0.81705463, 0.18294537],
       [0.59891677, 0.40108323],
       [0.73555972, 0.26444028],
       [0.40044821, 0.59955179],
       [0.81513745, 0.18486255],
       [0.59891677, 0.40108323],
       [0.09667872, 0.90332128],
       [0.32438652, 0.67561348],
       [0.15532088, 0.84467912],
       [0.67928358, 0.32071642],
       [0.53913316, 0.46086684],
       [0.

    testing with user input
  

In [ ]:
#User Input Function for Prediction
def predict_heart_disease():
    age = int(input("Enter age: "))
    cp = int(input("Enter chest pain type (0-3): "))
    thalach = int(input("Enter maximum heart rate achieved: "))
    user_data = pd.DataFrame([[age, cp, thalach]], columns=['age', 'cp', 'thalach'])
    prediction = model.predict(user_data)
    result = "Heart Disease Present" if prediction[0] == 1 else "No Heart Disease"
    print(f"Prediction: {result}")

# Call the user input function to test
predict_heart_disease()

Enter age: 20
Enter chest pain type (0-3): 50
Enter maximum heart rate achieved: 72
Prediction: Heart Disease Present


## save of model

In [ ]:
pip install joblib


In [ ]:
import joblib
joblib.dump(model, 'heart_disease_model.joblib')
print ("Model save succesfully")

Model save succesfully


## as per the model accuracy model got 72% accuracy which means 28% error thererfore, the model is capable 72% accurate